/* eslint-disable */
const compat = require('preact/compat');

module.exports = {
  createClass: require('@preact/legacy-compat').createClass,
  // createFactory: require('@preact/legacy-compat').createFactory,
  renderToString: require('preact-render-to-string'),
  ...compat,
  // createPortal,
  // createContext,
  // createRef,
  // createRoot,
  // forwardRef,
  // Fragment,
  // StrictMode,
  // AsyncMode,
  // ConcurrentMode,
  // Profiler,
  // PureComponent,
  // Suspense,
  // lazy,
  // memo,
  // useCallback,
  // useContext,
  // useDebugValue,
  // useEffect,
  // useImperativeHandle,
  // useLayoutEffect,
  // useMemo,
  // useReducer,
  // useRef,
  // useState,
  act: require('preact/test-utils').act,
};
