name: Continuous integration
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Format
        run: yarn checkformatting
      - name: Test (ESM)
        run: yarn test
      - name: Test (CommonJS)
        run: yarn test-cjs
      - name: Build and run examples
        run: node examples/run-all.js
